version: '3.1'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - thybak-bots-postgres:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  bots:
    build: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
      KKBOT_USERNAME: ${KKBOT_USERNAME}
      KKBOT_TOKEN: ${KKBOT_TOKEN}
      KKBOT_GROUP_CHAT_ID: ${KKBOT_GROUP_CHAT_ID}
    depends_on:
      - db
volumes:
  thybak-bots-postgres:
    external: false